# Generated by Django 4.2.7 on 2025-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "文本"), ("image", "图片"), ("audio", "语音")],
                default="text",
                max_length=20,
                verbose_name="消息类型",
            ),
        ),
    ]
