# Generated by Django 4.2.7 on 2025-07-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "注册验证"),
                            ("login", "登录验证"),
                            ("reset_password", "重置密码"),
                            ("change_phone", "更换手机号"),
                        ],
                        default="register",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="是否已使用"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="发送IP"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="验证尝试次数"),
                ),
            ],
            options={
                "verbose_name": "SMS验证码",
                "verbose_name_plural": "SMS验证码",
                "db_table": "sms_verification_code",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "created_at"],
                        name="sms_verific_phone_a9e383_idx",
                    ),
                    models.Index(
                        fields=["code", "is_used"], name="sms_verific_code_d88122_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="sms_verific_expires_cef3a6_idx"
                    ),
                ],
            },
        ),
    ]
