# Generated by Django 5.2.3 on 2025-06-19 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('role', models.CharField(choices=[('patient', '患者'), ('doctor', '医生'), ('admin', '管理员')], default='patient', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='执业证书号')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='科室')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='专业领域')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='身高(cm)')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='血型')),
                ('smoking_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='吸烟状况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='资料完整')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='过敏史')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='既往病史')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='家族史')),
                ('current_medications', models.TextField(blank=True, null=True, verbose_name='当前用药')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='启用提醒')),
                ('data_sharing_consent', models.BooleanField(default=False, verbose_name='数据共享同意')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_3744fd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_855a50_idx'),
        ),
    ]
