# Generated by Django 4.2.7 on 2025-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_chronic_diseases_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chronic_diseases",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="存储患者的慢性疾病ID列表。None=未评估，[]=健康，[diseases]=有疾病",
                null=True,
                verbose_name="慢性疾病列表",
            ),
        ),
    ]
