# Generated by Django 4.2.7 on 2025-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_smsverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chronic_diseases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="存储患者的慢性疾病ID列表",
                null=True,
                verbose_name="慢性疾病列表",
            ),
        ),
    ]
