# Generated by Django 4.2.7 on 2025-08-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_chronic_diseases_field"),
    ]

    operations = []
