# Generated by Django 5.1.4 on 2025-02-23 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("ProjectID", models.AutoField(primary_key=True, serialize=False)),
                ("ProjectName", models.CharField(max_length=100)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        limit_choices_to={"role": "employer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-StartDate"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField(auto_now_add=True)),
                ("role", models.CharField(max_length=30)),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"role": "employee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "employee")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                limit_choices_to={"role": "employee"},
                related_name="member_projects",
                through="product.ProjectMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
