# Generated by Django 4.2.7 on 2025-07-31 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("stopped", "已停药"),
                            ("paused", "已暂停"),
                        ],
                        max_length=20,
                        verbose_name="原状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("stopped", "已停药"),
                            ("paused", "已暂停"),
                        ],
                        max_length=20,
                        verbose_name="新状态",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="变更原因"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="附加说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="medication.medicationplan",
                        verbose_name="用药计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药状态变更历史",
                "verbose_name_plural": "用药状态变更历史",
                "db_table": "medication_status_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan", "created_at"],
                        name="medication__plan_id_3c3578_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "created_at"],
                        name="medication__changed_fb4a35_idx",
                    ),
                ],
            },
        ),
    ]
