"""
Django settings for chronic_disease_backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, source this from environment variables or a secret
# manager. Never hard-code real secrets into the repository.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production to disable detailed error pages and to
# reduce sensitive information exposure.
DEBUG = config('DEBUG', default=True, cast=bool)

# In production, restrict to your known domain(s)/IPs to mitigate Host
# header attacks.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.2.47']  # 限制为特定主机


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

LOCAL_APPS = [
    'accounts',
    'health',
    'medication',
    'communication',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 处理跨域资源共享，允许前端应用访问后端API
    'django.middleware.security.SecurityMiddleware',  # 提供基本的安全功能，如HTTPS重定向、安全头设置等
    'django.contrib.sessions.middleware.SessionMiddleware',  # 管理用户会话，支持用户登录状态保持
    'django.middleware.common.CommonMiddleware',  # 处理常见的HTTP请求处理任务
    'django.middleware.csrf.CsrfViewMiddleware',  # 防止跨站请求伪造攻击，保护表单提交安全
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 处理用户认证，为请求添加用户信息
    'django.contrib.messages.middleware.MessageMiddleware',  # 处理用户消息和通知的显示
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 防止页面被嵌入iframe进行点击劫持攻击
]

ROOT_URLCONF = 'chronic_disease_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 使用Django默认模板引擎
        'DIRS': [],  # 额外的模板目录列表，当前为空
        'APP_DIRS': True,  # 允许在已安装的应用中查找模板
        'OPTIONS': {
            'context_processors': [  # 上下文处理器，为所有模板提供通用变量
                'django.template.context_processors.debug',  # 提供debug变量
                'django.template.context_processors.request',  # 提供request对象到模板
                'django.contrib.auth.context_processors.auth',  # 提供用户认证相关变量
                'django.contrib.messages.context_processors.messages',  # 提供消息框架变量
            ],
        },
    },
]

WSGI_APPLICATION = 'chronic_disease_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 确保音频文件的MIME类型正确
import mimetypes
mimetypes.add_type('audio/m4a', '.m4a')
mimetypes.add_type('audio/mp4', '.m4a')
mimetypes.add_type('audio/mpeg', '.mp3')
mimetypes.add_type('audio/wav', '.wav')
mimetypes.add_type('audio/aac', '.aac')
mimetypes.add_type('audio/ogg', '.ogg')

# 音频文件处理设置
AUDIO_FILE_TYPES = {
    'm4a': 'audio/mp4',
    'mp3': 'audio/mpeg',
    'wav': 'audio/wav',
    'aac': 'audio/aac',
    'ogg': 'audio/ogg',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [  # 默认认证类列表
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT令牌认证
        'rest_framework.authentication.SessionAuthentication',  # 会话认证（备用方案）
    ],
    'DEFAULT_PERMISSION_CLASSES': [  # 默认权限类列表
        'rest_framework.permissions.IsAuthenticated',  # 要求用户必须已认证
    ],
    'DEFAULT_RENDERER_CLASSES': [  # 默认渲染器类列表
        'rest_framework.renderers.JSONRenderer',  # JSON格式响应渲染器
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # 默认分页类
    'PAGE_SIZE': 20,  # 每页显示的数据条数
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',  # 日期时间格式
    'DATE_FORMAT': '%Y-%m-%d',  # 日期格式
}

# JWT Settings
# JWT configuration. In production, prefer shorter access token lifetimes
# with refresh rotation and blacklist enabled, and store signing key out
# of code. Consider asymmetric algorithms for key separation.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),        # Access token expiry time: 1 day 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh token expiry time: 7 days 
    'ALGORITHM': 'HS256',                              # JWT signing algorithm 
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),    # Sliding token lifetime: 5 minutes 
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1), # Sliding token refresh lifetime: 1 day 
    'SIGNING_KEY': SECRET_KEY,                         # Secret key for signing 
    'VERIFYING_KEY': None,                             # Public key for verification (None for symmetric) 
    'AUDIENCE': None,                                  # Token audience claim 
    'ISSUER': None,                                    # Token issuer claim 
    'JWK_URL': None,                                   # JSON Web Key URL 
    'LEEWAY': 0,                                       # Clock skew tolerance in seconds 
    'AUTH_HEADER_TYPES': ('Bearer',),                  # Authorization header types 
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',          # Authorization header name 
    'USER_ID_FIELD': 'id',                             # User model ID field 
    'USER_ID_CLAIM': 'user_id',                        # User ID claim in token 
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',  # User authentication rule 
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Token classes for authentication 
    'TOKEN_TYPE_CLAIM': 'token_type',                  # Token type claim 
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',  # Token user class 
    'JTI_CLAIM': 'jti',                                # JWT ID claim 
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',  # Sliding token refresh expiry claim 
    'ROTATE_REFRESH_TOKENS': True,                     # Enable refresh token rotation 
    'BLACKLIST_AFTER_ROTATION': True,                  # Blacklist old tokens after rotation 
    'UPDATE_LAST_LOGIN': True,                         # Update last login timestamp 
    
}

# CORS settings - Allow React Native apps to access
# In production, keep this list tight and avoid `CORS_ALLOW_ALL_ORIGINS`.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",  # Expo default port
    "http://127.0.0.1:8081",
    "http://localhost:19006",  # Expo web port
    "http://127.0.0.1:19006",
    "http://192.168.2.47:8081",  # Your local IP:Expo port
    "http://192.168.2.47:19006",  # Your local IP:Expo Web port
]

# Development convenience only; must be False in production.
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all sources only in the development environment

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 健康指标相关设置
HEALTH_METRIC_TYPES = [
    ('blood_pressure', '血压'),
    ('blood_glucose', '血糖'),
    ('heart_rate', '心率'),
    ('weight', '体重'),
    ('uric_acid', '尿酸'),
    ('lipids', '血脂'),
]

# User Role Setting
USER_ROLES = [
    ('patient', '患者'),
    ('doctor', '医生'),
    ('admin', '管理员'),
]

# 性别选择
GENDER_CHOICES = [
    ('male', '男'),
    ('female', '女'),
]

# 用药相关设置
MEDICATION_FREQUENCIES = [
    ('QD', '每日一次'),
    ('BID', '每日两次'),
    ('TID', '每日三次'),
    ('QID', '每日四次'),
    ('Q12H', '每12小时一次'),
    ('Q8H', '每8小时一次'),
    ('Q6H', '每6小时一次'),
    ('PRN', '按需服用'),
]

MEDICATION_TIMES = [
    ('before_breakfast', '早餐前'),
    ('after_breakfast', '早餐后'),
    ('before_lunch', '午餐前'),
    ('after_lunch', '午餐后'),
    ('before_dinner', '晚餐前'),
    ('after_dinner', '晚餐后'),
    ('before_sleep', '睡前'),
    ('morning', '早晨'),
    ('noon', '中午'),
    ('evening', '晚上'),
]

# 告警状态
ALERT_STATUS_CHOICES = [
    ('pending', '待处理'),
    ('handled', '已处理'),
    ('dismissed', '已忽略'),
]

# 消息类型
MESSAGE_TYPES = [
    ('text', '文本'),
    ('image', '图片'),
    ('audio', '语音'),
]

# 日志配置 / Logging configuration
# Consider shipping logs to a centralized system (e.g., ELK/Cloud) and
# including request IDs for traceability in production.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'chronic_disease_backend': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# 创建日志目录
import os
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)
