# Generated by Django 4.2.7 on 2025-08-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_medicalhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalhistory',
            new_name='medical_his_patient_50861d_idx',
            old_name='medical_his_patient__3dc988_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalhistory',
            new_name='medical_his_history_45e917_idx',
            old_name='medical_his_history__2173a8_idx',
        ),
    ]
