[tool:pytest]
DJANGO_SETTINGS_MODULE = chronic_disease_backend.test_settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = 
    --tb=short
    --disable-warnings
    -ra
asyncio_default_fixture_loop_scope = function
markers =
    unit: 单元测试 - 测试独立的功能模块
    integration: 集成测试 - 测试API接口和组件交互
    api: API测试 - 测试REST API端点
    auth: 认证测试 - 测试登录注册等认证功能
    doctor: 医生角色测试 - 测试医生相关功能
    patient: 病人角色测试 - 测试病人相关功能
    health: 健康数据测试 - 测试健康指标管理
    medication: 用药管理测试 - 测试用药计划和提醒
    communication: 通信测试 - 测试医患沟通功能
    alert: 告警测试 - 测试智能告警系统
    slow: 慢速测试 - 运行时间较长的测试
    security: 安全测试 - 测试权限和安全功能
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning:django.*
    ignore::DeprecationWarning:rest_framework_simplejwt.*
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::DeprecationWarning:factory.*
    ignore::pytest.PytestDeprecationWarning:pytest_asyncio.*
    ignore::pytest.PytestUnknownMarkWarning