# Generated by Django 4.2.7 on 2025-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0002_medicationstatushistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationplan",
            name="time_of_day",
            field=models.JSONField(
                default=list,
                help_text='服药时间列表，如 ["08:00", "20:00"]',
                verbose_name="服药时间",
            ),
        ),
    ]
